-- INICIA TRANSAÇÃO

BEGIN TRANSACTION

--INSERE REGISTRO
INSERT INTO cadastro VALUES ('Andre', '123123')

-- CRIA UM PONTO DE RECUPERAÇÃO
SAVE TRANSACTION a1

--INSERE REGISTRO
INSERT INTO cadastro VALUES ('Joao', '312312')

-- CRIA UM PONTO DE RECUPERAÇÃO
SAVE TRANSACTION a2

--INSERE REGISTRO
INSERT INTO cadastro VALUES ('Pedro', '123111')

-- CRIA UM PONTO DE RECUPERAÇÃO
SAVE TRANSACTION a3

-- VERIFICA OS REGISTROS
SELECT * FROM cadastro

-- RESTAURA A TABELA ATÉ O PONTO a2
ROLLBACK TRANSACTION a2

-- RESTAURA TUDO
ROLLBACK

-- VERIFICA OS CADASTROS
SELECT * FROM cadastro

-- COMMIT NAS TRANSACTIONS
COMMIT TRANSACTION