use curso;

--DDL TRUNCATE
SELECT * FROM cidades
-- TRUNCATE TABLE cidades

-- FAZENDO BK EM TABELA TEMPORÁRIA
USE AdventureWorks2014
SELECT * INTO #HJTEMP FROM Person.Password
SELECT * FROM Person.Password

SELECT * FROM #HJTEMP

-- ANALISE DE REGISTROS ANTES DO TRUNCATE
SELECT COUNT(*) AS AntesTruncateCount
FROM Person.Password;

-- DDL TRUNCATE APAGAR DADOS DA TABELA

TRUNCATE TABLE Person.Password;

-- VERIFICANDO TABELAS APOS TRUNCATE
SELECT COUNT(*) AS DepoisTruncateCount
FROM Person.Password

--POPULANDO A TABELA COM DADOS DA TABELA TEMPORÁRIA

INSERT INTO Person.Password
SELECT * FROM #HJTEMP;

--VERIFICANDO REGISTROS

SELECT * FROM Person.Password